// Code generated by "stringer -type=OpOutcome"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpSucceeded-0]
	_ = x[OpFailed-1]
	_ = x[OpAborted-2]
	_ = x[OpSkipped-3]
	_ = x[OpWouldChange-4]
}

const _OpOutcome_name = "OpSucceededOpFailedOpAbortedOpSkippedOpWouldChange"

var _OpOutcome_index = [...]uint8{0, 11, 19, 28, 37, 50}

func (i OpOutcome) String() string {
	if i >= OpOutcome(len(_OpOutcome_index)-1) {
		return "OpOutcome(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpOutcome_name[_OpOutcome_index[i]:_OpOutcome_index[i+1]]
}
