// Code generated by "stringer -type=Impact"; DO NOT EDIT.

package diagnostic

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ImpactNone-0]
	_ = x[ImpactAbort-1]
}

const _Impact_name = "ImpactNoneImpactAbort"

var _Impact_index = [...]uint8{0, 10, 21}

func (i Impact) String() string {
	if i >= Impact(len(_Impact_index)-1) {
		return "Impact(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Impact_name[_Impact_index[i]:_Impact_index[i+1]]
}
