// SPDX-License-Identifier: GPL-3.0-only

// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Illegal-0]
	_ = x[EOF-1]
	_ = x[Semi-2]
	_ = x[Ident-3]
	_ = x[Int-4]
	_ = x[String-5]
	_ = x[StringBeg-6]
	_ = x[StringCont-7]
	_ = x[StringEnd-8]
	_ = x[StringMulti-9]
	_ = x[StringMultiBeg-10]
	_ = x[StringMultiCont-11]
	_ = x[StringMultiEnd-12]
	_ = x[LInterp-13]
	_ = x[RInterp-14]
	_ = x[Module-15]
	_ = x[Import-16]
	_ = x[Let-17]
	_ = x[Func-18]
	_ = x[Decl-19]
	_ = x[Type-20]
	_ = x[Enum-21]
	_ = x[For-22]
	_ = x[In-23]
	_ = x[If-24]
	_ = x[Else-25]
	_ = x[Return-26]
	_ = x[True-27]
	_ = x[False-28]
	_ = x[None-29]
	_ = x[Self-30]
	_ = x[Pub-31]
	_ = x[Plus-32]
	_ = x[Minus-33]
	_ = x[Star-34]
	_ = x[Slash-35]
	_ = x[Percent-36]
	_ = x[Eq-37]
	_ = x[Neq-38]
	_ = x[Lt-39]
	_ = x[Gt-40]
	_ = x[Leq-41]
	_ = x[Geq-42]
	_ = x[And-43]
	_ = x[Or-44]
	_ = x[Not-45]
	_ = x[Assign-46]
	_ = x[Colon-47]
	_ = x[Dot-48]
	_ = x[Question-49]
	_ = x[At-50]
	_ = x[LBrace-51]
	_ = x[RBrace-52]
	_ = x[LBrack-53]
	_ = x[RBrack-54]
	_ = x[LParen-55]
	_ = x[RParen-56]
	_ = x[Comma-57]
}

const _Kind_name = "IllegalEOFSemiIdentIntStringStringBegStringContStringEndStringMultiStringMultiBegStringMultiContStringMultiEndLInterpRInterpModuleImportLetFuncDeclTypeEnumForInIfElseReturnTrueFalseNoneSelfPubPlusMinusStarSlashPercentEqNeqLtGtLeqGeqAndOrNotAssignColonDotQuestionAtLBraceRBraceLBrackRBrackLParenRParenComma"

var _Kind_index = [...]uint16{0, 7, 10, 14, 19, 22, 28, 37, 47, 56, 67, 81, 96, 110, 117, 124, 130, 136, 139, 143, 147, 151, 155, 158, 160, 162, 166, 172, 176, 181, 185, 189, 192, 196, 201, 205, 210, 217, 219, 222, 224, 226, 229, 232, 235, 237, 240, 246, 251, 254, 262, 264, 270, 276, 282, 288, 294, 300, 305}

func (i Kind) String() string {
	if i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
