// Code generated by "stringer -type=Severity"; DO NOT EDIT.

package signal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Debug-0]
	_ = x[Info-1]
	_ = x[Notice-2]
	_ = x[Warning-3]
	_ = x[Error-4]
	_ = x[Fatal-5]
}

const _Severity_name = "DebugInfoNoticeWarningErrorFatal"

var _Severity_index = [...]uint8{0, 5, 9, 15, 22, 27, 32}

func (i Severity) String() string {
	if i >= Severity(len(_Severity_index)-1) {
		return "Severity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Severity_name[_Severity_index[i]:_Severity_index[i+1]]
}
