baseURL = "https://scampi.dev/"
languageCode = "en-us"
title = "scampi"
publishDir = "../build/site"

[module]
  [[module.imports]]
    path = "github.com/imfing/hextra"

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false

[params]
  description = "Declarative system convergence engine"
  displayUpdatedDate = false

  [params.navbar]
    displayTitle = true
    displayLogo = false

  [params.footer]
    displayPoweredBy = false

  [params.editURL]
    enable = true
    base = "https://github.com/scampi-dev/scampi/edit/main/site/content"

[[menus.main]]
  name = "About"
  pageRef = "/about"
  weight = 2
  [menus.main.params]
    type = "link"

[[menus.main]]
  name = "Examples"
  pageRef = "/examples"
  weight = 3
  [menus.main.params]
    type = "link"
    icon = "code"

[[menus.main]]
  name = "Install"
  pageRef = "/get"
  weight = 5
  [menus.main.params]
    type = "link"
    icon = "download"

[[menus.main]]
  name = "Search"
  weight = 6
  [menus.main.params]
    type = "search"

[[menus.main]]
  name = "GitHub"
  url = "https://github.com/scampi-dev/scampi"
  weight = 6
  [menus.main.params]
    icon = "github"
