// SPDX-License-Identifier: GPL-3.0-only

// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Illegal-0]
	_ = x[EOF-1]
	_ = x[Semi-2]
	_ = x[Ident-3]
	_ = x[Int-4]
	_ = x[String-5]
	_ = x[StringBeg-6]
	_ = x[StringCont-7]
	_ = x[StringEnd-8]
	_ = x[LInterp-9]
	_ = x[RInterp-10]
	_ = x[Module-11]
	_ = x[Import-12]
	_ = x[Let-13]
	_ = x[Func-14]
	_ = x[Decl-15]
	_ = x[Struct-16]
	_ = x[Enum-17]
	_ = x[For-18]
	_ = x[In-19]
	_ = x[If-20]
	_ = x[Else-21]
	_ = x[Return-22]
	_ = x[True-23]
	_ = x[False-24]
	_ = x[None-25]
	_ = x[Self-26]
	_ = x[Plus-27]
	_ = x[Minus-28]
	_ = x[Star-29]
	_ = x[Slash-30]
	_ = x[Percent-31]
	_ = x[Eq-32]
	_ = x[Neq-33]
	_ = x[Lt-34]
	_ = x[Gt-35]
	_ = x[Leq-36]
	_ = x[Geq-37]
	_ = x[And-38]
	_ = x[Or-39]
	_ = x[Not-40]
	_ = x[Assign-41]
	_ = x[Colon-42]
	_ = x[Dot-43]
	_ = x[Question-44]
	_ = x[LBrace-45]
	_ = x[RBrace-46]
	_ = x[LBrack-47]
	_ = x[RBrack-48]
	_ = x[LParen-49]
	_ = x[RParen-50]
	_ = x[Comma-51]
}

const _Kind_name = "IllegalEOFSemiIdentIntStringStringBegStringContStringEndLInterpRInterpModuleImportLetFuncDeclStructEnumForInIfElseReturnTrueFalseNoneSelfPlusMinusStarSlashPercentEqNeqLtGtLeqGeqAndOrNotAssignColonDotQuestionLBraceRBraceLBrackRBrackLParenRParenComma"

var _Kind_index = [...]uint8{0, 7, 10, 14, 19, 22, 28, 37, 47, 56, 63, 70, 76, 82, 85, 89, 93, 99, 103, 106, 108, 110, 114, 120, 124, 129, 133, 137, 141, 146, 150, 155, 162, 164, 167, 169, 171, 174, 177, 180, 182, 185, 191, 196, 199, 207, 213, 219, 225, 231, 237, 243, 248}

func (i Kind) String() string {
	if i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
