// Code generated by "stringer -type=stream"; DO NOT EDIT.

package cli

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[streamOut-0]
	_ = x[streamErr-1]
}

const _stream_name = "streamOutstreamErr"

var _stream_index = [...]uint8{0, 9, 18}

func (i stream) String() string {
	if i >= stream(len(_stream_index)-1) {
		return "stream(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _stream_name[_stream_index[i]:_stream_index[i+1]]
}
