#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-only
#
# bench/provision.sh — one-shot setup for the bench infrastructure.
#
# Creates everything bench/bench.sh needs:
#   - bench/.ssh/scampi_bench{,.pub}   ephemeral keypair (gitignored)
#   - bench/ansible/venv/              ansible venv from requirements.txt
#   - bench/ansible/inventory.ini      generated from .env
#   - 3 LXCs on the PVE host           via provision/lxcs.scampi
#   - perf-user inside each LXC        via provision/bootstrap.scampi
#   - 'pristine' snapshot per LXC      via provision/snapshot.scampi
#
# Idempotent — a converged target is a fast no-op pass. Re-run after
# changes to provision/, .env, or when something drifted upstream.
#
# Once this completes, run bash bench/bench.sh to time the workload.

set -euo pipefail

# shellcheck source=bench/lib.sh
source "$(dirname "$0")/lib.sh"

require_env_basics
require_scampi

# Generate an ephemeral SSH keypair for controller → bench-LXC comms
# if one isn't already there. Lives under bench/.ssh/ (gitignored)
# and goes away when the LXCs do.
ensure_ssh_key() {
    if [[ -f "$SSH_KEY_FILE" ]]; then
        return
    fi
    require ssh-keygen
    mkdir -p "$SSH_KEY_DIR"
    chmod 700 "$SSH_KEY_DIR"
    ssh-keygen -t ed25519 -f "$SSH_KEY_FILE" -N "" -C "scampi-bench" -q
    echo "generated bench keypair: ${SSH_KEY_FILE}{,.pub}"
}

# Set up the ansible venv from pinned requirements.txt if missing.
ensure_ansible_venv() {
    if [[ -x "$ANSIBLE" ]]; then
        return
    fi
    require python3
    echo "creating ansible venv at $ANSIBLE_VENV..."
    python3 -m venv "$ANSIBLE_VENV"
    "$ANSIBLE_VENV/bin/pip" install --quiet -r bench/ansible/requirements.txt
}

# Generate inventory.ini from the loaded env values. Always rewrites
# to keep it in sync with the current .env.
write_inventory() {
    local out=bench/ansible/inventory.ini
    {
        echo "# Generated by bench/provision.sh from bench/.env — do not edit by hand."
        echo "[bench]"
        for i in $(seq 0 $((BENCH_HOSTS - 1))); do
            echo "bench-$((i + 1)) ansible_host=${BENCH_IP_PREFIX}.$((BENCH_IP_BASE + i))"
        done
        echo
        echo "[bench:vars]"
        echo "ansible_user=${BENCH_USER}"
        echo "ansible_python_interpreter=/usr/bin/python3"
        echo "ansible_ssh_private_key_file=${SCAMPI_BENCH_SSH_KEY}"
    } > "$out"
}

ensure_ssh_key
export_ssh_env       # absolute SCAMPI_BENCH_SSH_KEY needed by write_inventory
ensure_ansible_venv
write_inventory

# Apply the three provision phases sequentially. std.deploy blocks
# within one file run in parallel; bootstrap (phase 2) and snapshot
# (phase 3) need the LXCs from phase 1 to exist first, so they're
# separate files applied in order.
for phase in lxcs bootstrap snapshot; do
    echo "→ bench/provision/${phase}.scampi"
    "$SCAMPI" apply "bench/provision/${phase}.scampi"
done

echo
echo "provisioned. run bash bench/bench.sh to time the workload."
