// SPDX-License-Identifier: GPL-3.0-only

// Code generated by "stringer -type=CauseKind"; DO NOT EDIT.

package event

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CauseNone-0]
	_ = x[CauseHook-1]
}

const _CauseKind_name = "CauseNoneCauseHook"

var _CauseKind_index = [...]uint8{0, 9, 18}

func (i CauseKind) String() string {
	if i >= CauseKind(len(_CauseKind_index)-1) {
		return "CauseKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CauseKind_name[_CauseKind_index[i]:_CauseKind_index[i+1]]
}
