// SPDX-License-Identifier: GPL-3.0-only

package rules

import (
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// nerdPUAStart is the first codepoint of supplementary private use area A,
// where Nerd Font icons live. Box drawing and braille (the spinner frames)
// are ordinary codepoints every monospace font carries, so they need no
// subset and are excluded here.
const nerdPUAStart = 0xF0000

// Test_Rule_FontSubset pins site/data/glyphs.json to the glyph set in
// render/cli/glyph.go.
//
// The site embeds terminal transcripts containing CLI glyphs and ships a
// font subset carrying exactly them. The subset and its CSS unicode-range
// are generated by scripts/site-fonts.sh from glyph.go; this rule fails if
// they drift, so a new glyph cannot reach the site without the font being
// rebuilt.
//
// The previous hand-maintained subset had three codepoints each one digit
// off from a real glyph, which rendered as tofu on a live page. Hence a rule
// rather than a convention.
func Test_Rule_FontSubset(t *testing.T) {
	repo := repoRoot(t)

	src, err := os.ReadFile(filepath.Join(repo, "internal", "render", "cli", "glyph.go"))
	if err != nil {
		t.Fatalf("read glyph.go: %v", err)
	}

	seen := map[rune]bool{}
	for _, r := range string(src) {
		if r >= nerdPUAStart {
			seen[r] = true
		}
	}
	if len(seen) == 0 {
		t.Fatal("no Nerd Font codepoints found in glyph.go -- has the glyph set moved?")
	}

	want := make([]string, 0, len(seen))
	for r := range seen {
		want = append(want, fmt.Sprintf("U+%04X", r))
	}
	sort.Strings(want)

	data, err := os.ReadFile(filepath.Join(repo, "site", "data", "glyphs.json"))
	if err != nil {
		t.Fatalf("read site/data/glyphs.json: %v -- run `just site fonts`", err)
	}

	var glyphs struct {
		UnicodeRange string `json:"unicodeRange"`
		FontSHA256   string `json:"fontSha256"`
	}
	if err := json.Unmarshal(data, &glyphs); err != nil {
		t.Fatalf("parse glyphs.json: %v", err)
	}

	// The codepoint list alone is not enough: a stale woff2 alongside a
	// correct list would pass. pyftsubset is deterministic for a given
	// input and version, so the hash pins the actual font bytes.
	font, err := os.ReadFile(filepath.Join(repo, "site", "static", "fonts", "nerd-symbols-subset.woff2"))
	if err != nil {
		t.Fatalf("read font subset: %v -- run `just site fonts`", err)
	}
	if sum := fmt.Sprintf("%x", sha256.Sum256(font)); sum != glyphs.FontSHA256 {
		t.Errorf("font subset does not match glyphs.json -- run `just site fonts`\n  want: %s\n  got:  %s",
			glyphs.FontSHA256, sum)
	}

	var got []string
	for _, part := range strings.Split(glyphs.UnicodeRange, ",") {
		if p := strings.TrimSpace(part); p != "" {
			got = append(got, p)
		}
	}
	sort.Strings(got)

	if strings.Join(got, ",") != strings.Join(want, ",") {
		t.Errorf("site font subset is stale -- run `just site fonts`\n  glyph.go: %s\n  glyphs.json: %s",
			strings.Join(want, ","), strings.Join(got, ","))
	}
}
