// SPDX-License-Identifier: GPL-3.0-only

// Code generated by "stringer -type=ColorMode"; DO NOT EDIT.

package signal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ColorAuto-0]
	_ = x[ColorAlways-1]
	_ = x[ColorNever-2]
}

const _ColorMode_name = "ColorAutoColorAlwaysColorNever"

var _ColorMode_index = [...]uint8{0, 9, 20, 30}

func (i ColorMode) String() string {
	if i >= ColorMode(len(_ColorMode_index)-1) {
		return "ColorMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ColorMode_name[_ColorMode_index[i]:_ColorMode_index[i+1]]
}
