// SPDX-License-Identifier: GPL-3.0-only

// Code generated by "stringer -type=Severity"; DO NOT EDIT.

package signal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Info-0]
	_ = x[Warning-1]
	_ = x[Error-2]
}

const _Severity_name = "InfoWarningError"

var _Severity_index = [...]uint8{0, 4, 11, 16}

func (i Severity) String() string {
	if i >= Severity(len(_Severity_index)-1) {
		return "Severity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Severity_name[_Severity_index[i]:_Severity_index[i+1]]
}
