// SPDX-License-Identifier: GPL-3.0-only

// Code generated by "stringer -type=Verbosity"; DO NOT EDIT.

package signal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Quiet-0]
	_ = x[V-1]
	_ = x[VV-2]
	_ = x[VVV-3]
}

const _Verbosity_name = "QuietVVVVVV"

var _Verbosity_index = [...]uint8{0, 5, 6, 8, 11}

func (i Verbosity) String() string {
	if i >= Verbosity(len(_Verbosity_index)-1) {
		return "Verbosity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Verbosity_name[_Verbosity_index[i]:_Verbosity_index[i+1]]
}
