#!/usr/bin/env python3
"""Generate a verification report of diagnostic test span expectations.

Reads each test case in test/testdata/diagnostics/ and produces a markdown
document showing the config source with the expected span underlined.

Usage:
    python3 scripts/diagnostic-span-report.py > report.md
"""

import json
import os
import sys


def load_expect(path):
    with open(path) as f:
        return json.load(f)


def load_config(path):
    with open(path) as f:
        return f.read()


def underline(line_text, start_col, end_col):
    """Produce a caret/tilde underline string for the given column range."""
    if start_col <= 0 and end_col <= 0:
        return None

    # Columns are 1-based in the spans.
    pad = " " * (start_col - 1) if start_col > 0 else ""
    width = max(end_col - start_col, 0)
    if width == 0:
        return pad + "^"
    return pad + "^" + "~" * (width - 1)


def process_case(name, dir_path):
    entries = []

    for expect_name in sorted(os.listdir(dir_path)):
        if not expect_name.startswith("expect") or not expect_name.endswith(".json"):
            continue

        expect_path = os.path.join(dir_path, expect_name)
        data = load_expect(expect_path)

        config_name = "config.scampi"
        config_path = os.path.join(dir_path, config_name)
        if not os.path.exists(config_path):
            continue

        config = load_config(config_path)
        lines = config.splitlines()

        for diag in data.get("diagnostics", []):
            src = diag.get("source")
            if not src:
                continue

            sl = src.get("start_line", 0)
            sc = src.get("start_col", 0)
            el = src.get("end_line", 0)
            ec = src.get("end_col", 0)
            diag_id = diag.get("id", "?")

            suffix = ""
            if expect_name != "expect.json":
                suffix = f" ({expect_name})"

            entry = []
            entry.append(f"## {name}{suffix} ({diag_id})")
            entry.append("")
            entry.append("```")
            for i, line in enumerate(lines, 1):
                entry.append(f"  {i:>3} | {line}")
                if sl == el and i == sl:
                    ul = underline(line, sc, ec)
                    if ul:
                        entry.append(f"        {ul}")
                elif sl != el:
                    if i == sl:
                        ul = underline(line, sc, len(line) + 1)
                        if ul:
                            entry.append(f"        {ul}")
                    elif i == el:
                        ul = underline(line, 1, ec)
                        if ul:
                            entry.append(f"        {ul}")
            entry.append("```")
            entry.append("")

            if sc == 0 and ec == 0:
                entry.append(f"span: {sl}:0 → {el}:0 (no column precision)")
            else:
                entry.append(f"span: {sl}:{sc} → {el}:{ec}")
            entry.append("")

            entries.append("\n".join(entry))

    return entries


def main():
    root = os.path.join(os.path.dirname(__file__), "..", "test", "testdata", "diagnostics")
    root = os.path.normpath(root)

    print("# Diagnostic Span Verification Report")
    print()
    print("Auto-generated by `scripts/diagnostic-span-report.py`.")
    print("Shows each diagnostic test case with the expected source span underlined.")
    print()

    dirs = sorted(d for d in os.listdir(root) if os.path.isdir(os.path.join(root, d)))

    for name in dirs:
        dir_path = os.path.join(root, name)
        entries = process_case(name, dir_path)
        for entry in entries:
            print(entry)


if __name__ == "__main__":
    main()
