#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-only
#
# Stage a release: tag the current HEAD with the next version.
# Usage: release.sh [alpha|beta|rc] [--dry-run]
#
# Release notes are generated by GitHub from commits since the previous
# tag — no local CHANGELOG.md to maintain. After staging, run
# `just release push` to publish.
set -euo pipefail

dir="$(cd "$(dirname "$0")" && pwd)"

stage=""
dry_run=false

while [[ $# -gt 0 ]]; do
  case "$1" in
  alpha | beta | rc) stage="$1"; shift ;;
  --dry-run)         dry_run=true; shift ;;
  *) echo "usage: release.sh [alpha|beta|rc] [--dry-run]" >&2; exit 1 ;;
  esac
done

# Clean tree check
if [[ -n "$(git status --porcelain)" ]]; then
  echo "error: working tree is dirty -- commit or stash first" >&2
  exit 1
fi

# Compute version
# shellcheck disable=SC2086
version=$("$dir/next-version.sh" $stage)
echo "next version: $version"

if [[ "$dry_run" == true ]]; then
  echo "--- dry run: would tag $version on $(git rev-parse --short HEAD) ---"
  exit 0
fi

git tag -a "$version" -m "$version"
echo "tagged $version"
