// SPDX-License-Identifier: GPL-3.0-only

// Code generated by "stringer -type=CheckResult"; DO NOT EDIT.

package spec

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CheckUnknown-0]
	_ = x[CheckSatisfied-1]
	_ = x[CheckUnsatisfied-2]
}

const _CheckResult_name = "CheckUnknownCheckSatisfiedCheckUnsatisfied"

var _CheckResult_index = [...]uint8{0, 12, 26, 42}

func (i CheckResult) String() string {
	if i >= CheckResult(len(_CheckResult_index)-1) {
		return "CheckResult(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CheckResult_name[_CheckResult_index[i]:_CheckResult_index[i+1]]
}
