// SPDX-License-Identifier: GPL-3.0-only

package spec

// SourceRefKind identifies how a source was provided.
type SourceRefKind uint8

const (
	SourceLocal SourceRefKind = iota
	SourceInline
	SourceRemote
	// SourceTarget reads from a path on the *target* (the system being
	// converged), not from the source side. Use cases: copying a file
	// generated by a previous step on the same target, propagating a
	// config file across paths without round-tripping through the
	// source. Symlink covers most of this need; SourceTarget is for
	// the cases where two independent copies (with separate
	// ownership/perm management) are wanted. See #286.
	SourceTarget
)

// SourceRef is a resolved reference to source content. For local and inline
// sources, Path is set at eval time. For remote sources, Path is the
// deterministic cache path where the download op will write the file.
// For SourceTarget, Path is the literal target-side path read at apply time.
type SourceRef struct {
	Kind     SourceRefKind
	Path     string   // cache path (set for all kinds after eval)
	Content  string   // SourceInline only: original content (for display/diagnostics)
	URL      string   // SourceRemote only: download URL
	Checksum Checksum // SourceRemote only: expected checksum
}

func (r SourceRef) NeedsResolution() bool {
	return r.Kind == SourceRemote
}

func (r SourceRef) IsZero() bool {
	return r.Path == "" && r.Content == "" && r.URL == ""
}

func (r SourceRef) DisplayPath() string {
	switch r.Kind {
	case SourceInline:
		return "(inline)"
	case SourceRemote:
		return r.URL
	case SourceTarget:
		return "(target:" + r.Path + ")"
	default:
		return r.Path
	}
}
