// SPDX-License-Identifier: GPL-3.0-only

// Code generated by "stringer -type=ChangePhase"; DO NOT EDIT.

package event

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ChangePlanned-0]
	_ = x[ChangeExecuted-1]
}

const _ChangePhase_name = "ChangePlannedChangeExecuted"

var _ChangePhase_index = [...]uint8{0, 13, 27}

func (i ChangePhase) String() string {
	if i >= ChangePhase(len(_ChangePhase_index)-1) {
		return "ChangePhase(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ChangePhase_name[_ChangePhase_index[i]:_ChangePhase_index[i+1]]
}
