// SPDX-License-Identifier: GPL-3.0-only

// Code generated by "stringer -type=EngineKind"; DO NOT EDIT.

package event

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EngineStarted-0]
	_ = x[EngineConnecting-1]
	_ = x[EngineFinished-2]
}

const _EngineKind_name = "EngineStartedEngineConnectingEngineFinished"

var _EngineKind_index = [...]uint8{0, 13, 29, 43}

func (i EngineKind) String() string {
	if i >= EngineKind(len(_EngineKind_index)-1) {
		return "EngineKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EngineKind_name[_EngineKind_index[i]:_EngineKind_index[i+1]]
}
